### ISSUE TITLE
GPS Airborne Mode?

### ISSUE THREAD

**Issue by darksidelemm** [RoelKroes/HorusBinary_Tracker#1]
Maybe I missed it - are you setting the uBlox GPS into airborne mode? 
If not, this tracker code will likely lose GPS lock above 18km altitude - not ideal!

**Comment by RoelKroes** [comment]
Hi Mark,

You are absolutely right about that.
 
I removed the code for setting GPS modes in the RTTY, 4FSK and LoRa trackers to save some memory and keep the code small enough for the Arduino Pro Mini and leave some extra space for sensors.  

I choose that code because I think this sketch is mainly used for pico balloons that usually stay below 18km and use the (less reliable but cheaper) atgm336h GPS modules which do not need to switch modes.

Perhaps, in retrospect, that was the wrong decision as I got more remarks about that already :-( 
I probably figure out a way to get that code in again.

Roel.
